language: generic
env:
  global:
    - IDE_VERSION=1.6.8
  matrix:
    - BOARD="arduino:avr:uno"
    - BOARD="arduino:avr:leonardo"
    - BOARD="arduino:avr:mega:cpu=atmega2560"
    - BOARD="arduino:sam:arduino_due_x_dbg"
    - BOARD="arduino:samd:arduino_zero_edbg"
    - BOARD="arduino:samd:mkr1000"
    - BOARD="Intel:arc32:arduino_101"
matrix:
  allow_failures:
    - env: BOARD="arduino:avr:leonardo"
    - env: BOARD="arduino:sam:arduino_due_x_dbg"
    - env: BOARD="Intel:arc32:arduino_101"
before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "arduino:sam:" ]]; then
      arduino --install-boards arduino:sam;
    fi
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino --install-boards arduino:samd;
    fi
  - if [[ "$BOARD" =~ "Intel:arc32" ]]; then
      arduino --install-boards Intel:arc32;
    fi
  - buildExampleSketch() { arduino --verbose-build --verify --board $BOARD $PWD/examples/$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - buildExampleSketch hello_menu
  - buildExampleSketch serial_menu
  - buildExampleSketch buttons_menu
  - buildExampleSketch functions_menu
  - buildExampleSketch focus_menu
  - buildExampleSketch system_menu
